spring:
  application:
    name: tda26

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/tda_app}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:TenBobr69!}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # PŘIDÁNO: Oprava pro Hibernate 6 dědičnost JOINED a agregace
        query:
          in_clause_parameter_padding: true
          sqm:
            mutation_strategy: inline
        criteria:
          copy_tree: true

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      enabled: true

  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:./uploads/

  security:
    user:
      name: lecturer
      password: TdA26!

#  mvc:
#    throw-exception-if-no-handler-found: true

server:
  port: 8080
  error:
    include-message: always

springdoc:
  api-docs:
    path: /api
  swagger-ui:
    path: /swagger-ui.html

file:
  upload-dir: ./uploads
