name: Build and push Web App to TdA

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t tda26-spring .
          docker build -t tda26-react ./frontend
          docker build -t tda26-caddy ./caddy

      - name: Upload to TdA
        uses: Student-Cyber-Games/upload-app@tda-26
        with:
          tdc_token: ${{ secrets.TDC_TOKEN }}
